### ISSUE TITLE
Not able to collect the stats.

### ISSUE THREAD

**Issue by hacktvist** [HubSpot/BuckyClient#35]
while trying to collect the stats, i am getting this error:

Collecting example.com.page.navigationStart, example.com.page.fetchStart, example.com.page.domainLookupStart, example.com.page.domainLookupEnd, example.com.page.connectStart, example.com.page.connectEnd, example.com.page.requestStart, example.com.page.responseStart, example.com.page.responseEnd, example.com.page.domLoading, example.com.page.domInteractive, example.com.page.domContentLoadedEventStart, example.com.page.toJSON for ::ffff:192.168.0.1
Unparsable row: NaN|ms
TypeError: Cannot read property '0' of undefined
    at Client.write (/home/site/BuckyServer/lib/opentsdb.coffee:25:47)
    at next.send (/home/site/BuckyServer/modules/openTSDB.coffee:14:25)
    at /home/site/BuckyServer/modules/collectors.coffee:22:25
    at callbacks (/home/site/BuckyServer/node_modules/express/lib/router/index.js:161:37)
    at next.send (/home/site/BuckyServer/modules/auth.coffee:7:16)
    at callbacks (/home/site/BuckyServer/node_modules/express/lib/router/index.js:161:37)
    at IncomingMessage.<anonymous> (/home/site/BuckyServer/server.coffee:58:14)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by fc** [comment]
What appears to have happened is that you're using the npm version of bucky (me too) since the issue is currently fixed in their master branch:
https://github.com/HubSpot/BuckyClient/blob/master/bucky.js#L393

If you want to only update your version of bucky.js then update the code around line 351 (for the npm version of bucky.js) to this:
```        for (key in _ref5) {
          time = _ref5[key];
          if (typeof time === 'number') {
            timer.send("" + path + "." + key, time - start);
          }
        }
```

Otherwise, get the latest from here:
https://raw.githubusercontent.com/HubSpot/BuckyClient/master/bucky.js

After this you may get connection errors because opentsdb and influxdb are not installed.  On macOS you can install them with `brew install opentsdb influxdb` then start the related services - including starting `hbase` which is a dependency of opentsdb.

It should also be noted that the wrappers to feed the data into opentsdb/influxdb don't work with the latest versions of opentsdb/influxdb.  Haven't yet tested with statsd yet.
